name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
       os: [ubuntu-latest]
       #os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore source/TSC.Shared/TSC.Shared.csproj
    - name: Install GPR
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: dotnet tool install gpr -g
    - name: Build
      run: dotnet build source/TSC.Shared/TSC.Shared.csproj --configuration Release --no-restore
    #- name: Test
      #run: dotnet test --no-restore --verbosity normal
    - name: Pack
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID source/TSC.Shared/TSC.Shared.csproj
    - name: Upload Artifact
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: dotnet nuget push "source/TSC.Shared/bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/rcangus/index.json" --skip-duplicate
      #run: gpr push "source/TSC.Shared/bin/Release/*.nupkg" -k ${{ secrets.PACKAGES_PAT }}
      #uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      #with:
      ##  nupkg-path:  './source/TSC.Shared/bin/Release/*.nupkg'
      #  repo-owner:  'rcangus'
      #  gh-user:  'rcangus'
      #  token:  ${{ secrets.GITHUB_TOKEN }}
    #  run: dotnet nuget push "source/bin/Release/TSC.Shared.1.0.0.nupkg" --source "github"